apiVersion: v1
kind: Service
metadata: 
    name: {{ .Values.payment.name }}
    labels: 
        owner: AlexanderFedoseeff
spec:
    selector:
        app: {{ .Values.payment.name }}
    ports:
      - name: {{ .Values.payment.name }}-listener
        protocol: TCP
        port: {{ .Values.payment.port }}
        targetPort: {{ .Values.payment.name }}
